
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/proAuto
    username: postgres
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 7777

